# Generated by Django 3.0 on 2020-03-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_sub', '0010_auto_20200226_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='salt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
