# Generated by Django 3.0.4 on 2020-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_auto_20200321_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un compte est déjà créé avec ce courriel.'}, max_length=255, unique=True, verbose_name='Courriel'),
        ),
    ]
