# Generated by Django 3.0 on 2020-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('off_sub', '0002_auto_20200211_1647'),
        ('my_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='interested_users', to='off_sub.Product'),
        ),
    ]
